### ISSUE TITLE
prepare_wikipedia.py references missing module lcm.datasets.sentence_splitter_pipeline 

### ISSUE THREAD

**Issue by danhussey** [facebookresearch/large_concept_model#1]
Hello,

Thanks for publishing this code. I'm trying to get a data processing run going on a fresh Ubuntu 22.04 install using `prepare_wikipedia.py`.

## System Overview
```bash
(large-concept-model) root@b5ca3817f042:~/Code/large_concept_model# pip list | grep large
large-concept-model               0.1.0         /root/Code/large_concept_model
```
- Fresh Ubuntu 22.04 install.

Commit:
```bash
(large-concept-model) root@b5ca3817f042:~/Code/large_concept_model# git log
commit 1ceb6da841b2f962e24b0593b5cbc0dc1c8c320a (HEAD -> main, origin/main, origin/HEAD)
```

## Expected behaviour
Running 
`python -m lcm.datasets.prepare_wikipedia data/`
should kick off a data processing pipeline after installing required packages and the large-concept-model package.

## Actual behaviour
I get an error:

```shell
(large-concept-model) root@b5ca3817f042:~/Code/large_concept_model# python -m lcm.datasets.prepare_wikipedia data/
2024-12-14 11:28 INFO 3486:datasets - PyTorch version 2.5.1+cu121 available.
2024-12-14 11:28 INFO 3486:datasets - Polars version 1.17.1 available.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/Code/large_concept_model/lcm/datasets/prepare_wikipedia.py", line 23, in <module>
    from lcm.datasets.sentence_splitter_pipeline import (
ModuleNotFoundError: No module named 'lcm.datasets.sentence_splitter_pipeline'
``` 
## Notes
There doesn't seem to be any file in the repo called `sentence_splitter_pipeline`, or to the things attempted to be imported from there and used in `prepare_wikipedia.py`, like `SentenceSplitterConfig` on line 38-47:
```python
    # setup the sentence splitter
    splitter_config = SentenceSplitterConfig(
        columns=[
            "text"
        ],  # this is the column in the input dataset where we expect to find text to split
        model_name="sat-3l",
        verbose=True,
        sentence_threshold=0.02,
        max_sentence_len=256,
    )
``` 

Maybe some of this got left out?

## Summary
`tcm.sentence_splitter_pipeline`, along with its `SentenceSplitterConfig` seems missing, which is required for `prepare_wikipedia.py`

Thanks, Daniel.

**Comment by elbayadm** [comment]
Hi, Daniel! 
Thank you for opening this issue. The file was indeed missing. PR #2 should solve the problem. Please let me know if you still face issues with the data preparation script.

**Comment by danhussey** [comment]
Hi Maha, just tested after pulling latest and it's all working now. Thanks very much!
