### ISSUE TITLE
Request for Pretrained Checkpoints

### ISSUE THREAD

**Issue by xboldt** [facebookresearch/large_concept_model#4]
Dear LCM team,

thank you for sharing your work on large concept models! I appreciate the effort you put into providing the code additionally to the paper.
I was wondering if you could share any pretrained checkpoints for any of the models described in the paper?

**Comment by Ostovane** [comment]
> We are sorry but there is currently no plan to open source the weights of the pre-trained or finetuned models.

I think there’s an opportunity to elevate the quality of this work further.
